### ISSUE TITLE
Erros do Projeto em 11/04

### ISSUE THREAD

**Issue by glaucotodesco** [shiiiro018/projeto-poo2#3]
O mapeamento não está correto e existe um erro ao executar o Main para criar as tabelas.
O erro de ontem é que vocês usaram ArrayList como tipo e não List
Falta ainda colocar os mapeamentos OneToMany e ManyToOne como na classe Cliente no atributo pedidos:

   @OneToMany
   private List<Pedido> pedidos = new ArrayList<>();

Vocês precisam terminar o mapeamento de todas as classes, alterar o Main.java para criar todas as tabelas e popular com dados todas as tabelas do projeto ao executar o Main.java

Outra coisa, cadê a Jessica como membro do grupo?

**Comment by glaucotodesco** [comment]
Na aplicação WEB falta:
* o excluir e alterar funcionar para o Cliente
* Categoria tem erro no XHTML e ele não abre

**Comment by shiiiro018** [comment]
Boa tarde Glauco, tudo bem?
Esses erros a gente pode corrigir antes de te enviar a master hoje ou só no
próximo módulo?
E eu acho que a Jéssica não aceitou o convite de colaborador, porque eu
adicionei ela lá.

Em qui, 11 de abr de 2019 às 11:30, glaucotodesco <notifications@github.com>
escreveu:

**Comment by glaucotodesco** [comment]
Até hoje ainda é possível
